"use client";

import { useEffect, useState } from "react";
import { supabase, isSupabaseConfigured } from "@/lib/supabaseClient";
import { 
  Users, Smartphone, Clock, MapPin, Globe, Compass, 
  Terminal, CheckCircle, AlertTriangle, RefreshCw, ArrowLeft, Cpu, Monitor, ShieldCheck, Copy, Check, Eye
} from "lucide-react";
import Link from "next/link";

export default function VisitorDashboard() {
  const [visitors, setVisitors] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [refetching, setRefetching] = useState(false);
  const [dataSource, setDataSource] = useState("none"); // "supabase" | "local" | "none"
  const [copied, setCopied] = useState(false);

  const sqlSchema = `-- 1. Crie a tabela de visitantes no painel do Supabase com chave única de visitante
create table visitors (
  id bigint generated by default as identity primary key,
  visitor_uuid text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_mobile boolean default false,
  location_city text,
  location_country text,
  location_country_code text,
  location_region text,
  browser_name text,
  browser_version text,
  os_name text,
  device_model text,
  screen_resolution text,
  language text,
  session_duration integer default 0,
  visit_count integer default 1,
  page_visited text,
  ip_address text,
  last_active timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Ativar segurança em nível de linha (RLS)
alter table visitors enable row level security;

-- 3. Criar políticas públicas para inserção, atualização e leitura
create policy "Allow public inserts" on visitors for insert with check (true);
create policy "Allow public updates" on visitors for update using (true);
create policy "Allow public select" on visitors for select using (true);`;

  const getCountryFlag = (code) => {
    if (!code || code.length !== 2) return "🌐";
    const charCode1 = code.charCodeAt(0) + 127397;
    const charCode2 = code.charCodeAt(1) + 127397;
    try {
      return String.fromCodePoint(charCode1, charCode2);
    } catch (e) {
      return "🌐";
    }
  };

  const formatDuration = (seconds) => {
    if (!seconds && seconds !== 0) return "0s";
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    if (m > 0) return `${m}m ${s}s`;
    return `${s}s`;
  };

  const formatTimeAgo = (dateString) => {
    try {
      const date = new Date(dateString);
      const seconds = Math.floor((new Date() - date) / 1000);
      if (seconds < 10) return "Agora mesmo";
      if (seconds < 60) return `Há ${seconds}s`;
      const minutes = Math.floor(seconds / 60);
      if (minutes < 60) return `Há ${minutes}m`;
      const hours = Math.floor(minutes / 60);
      if (hours < 24) return `Há ${hours}h`;
      return date.toLocaleDateString("pt-MZ");
    } catch (e) {
      return "Indisponível";
    }
  };

  const fetchVisitors = async (showRefetchAnim = false) => {
    if (showRefetchAnim) setRefetching(true);
    setIsLoading(true);

    if (isSupabaseConfigured && supabase) {
      try {
        const { data, error } = await supabase
          .from("visitors")
          .select("*")
          .order("last_active", { ascending: false })
          .limit(10);

        if (!error && data) {
          setVisitors(data);
          setDataSource("supabase");
          setIsLoading(false);
          if (showRefetchAnim) setRefetching(false);
          return;
        } else {
          console.error("Error retrieving Supabase logs:", error);
        }
      } catch (err) {
        console.error("Supabase fetch exception:", err);
      }
    }

    // Fallback to local storage logs
    try {
      const localLogs = JSON.parse(localStorage.getItem("zuca_local_visitors") || "[]");
      // Sort localLogs by last_active descending
      const sortedLogs = localLogs.sort((a, b) => new Date(b.last_active) - new Date(a.last_active)).slice(0, 10);
      setVisitors(sortedLogs);
      setDataSource(sortedLogs.length > 0 ? "local" : "none");
    } catch (err) {
      console.warn("Failed to retrieve local visitor logs:", err);
      setDataSource("none");
    }

    setIsLoading(false);
    if (showRefetchAnim) setRefetching(false);
  };

  const generateMockData = () => {
    const mockVisitors = [
      {
        id: "mock_1",
        visitor_uuid: "vis_mock_uuid_101",
        created_at: new Date(Date.now() - 30 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Maputo",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Maputo Cidade",
        browser_name: "Chrome",
        browser_version: "125.0.0",
        os_name: "Android",
        device_model: "Samsung Galaxy S24 Ultra (SM-S928B)",
        screen_resolution: "412x915",
        language: "pt-MZ",
        session_duration: 30,
        visit_count: 3,
        page_visited: "/",
        ip_address: "102.219.124.5",
        last_active: new Date().toISOString()
      },
      {
        id: "mock_2",
        visitor_uuid: "vis_mock_uuid_102",
        created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Matola",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Maputo Província",
        browser_name: "Safari",
        browser_version: "17.4",
        os_name: "iOS",
        device_model: "Apple iPhone 15 Pro Max",
        screen_resolution: "430x932",
        language: "pt-PT",
        session_duration: 180,
        visit_count: 5,
        page_visited: "/emergencia",
        ip_address: "102.217.45.18",
        last_active: new Date(Date.now() - 10000).toISOString()
      },
      {
        id: "mock_3",
        visitor_uuid: "vis_mock_uuid_103",
        created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        is_mobile: false,
        location_city: "Lisboa",
        location_country: "Portugal",
        location_country_code: "PT",
        location_region: "Lisboa Distrito",
        browser_name: "Firefox",
        browser_version: "126.0",
        os_name: "Windows",
        device_model: "Windows PC",
        screen_resolution: "1920x1080",
        language: "pt-PT",
        session_duration: 450,
        visit_count: 2,
        page_visited: "/vagas",
        ip_address: "94.60.180.20",
        last_active: new Date(Date.now() - 5 * 60 * 1000).toISOString()
      },
      {
        id: "mock_4",
        visitor_uuid: "vis_mock_uuid_104",
        created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Beira",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Sofala",
        browser_name: "Chrome",
        browser_version: "124.0.0",
        os_name: "Android",
        device_model: "Xiaomi Redmi Note 13 Pro",
        screen_resolution: "393x873",
        language: "en-US",
        session_duration: 12,
        visit_count: 1,
        page_visited: "/farmacias",
        ip_address: "196.28.32.90",
        last_active: new Date(Date.now() - 44 * 60 * 1000).toISOString()
      },
      {
        id: "mock_5",
        visitor_uuid: "vis_mock_uuid_105",
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        is_mobile: false,
        location_city: "Nampula",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Nampula",
        browser_name: "Edge",
        browser_version: "124.0",
        os_name: "macOS",
        device_model: "Apple Mac (M3 MacBook Air)",
        screen_resolution: "1470x956",
        language: "pt-MZ",
        session_duration: 1200,
        visit_count: 9,
        page_visited: "/reportar",
        ip_address: "41.223.111.4",
        last_active: new Date(Date.now() - 1.8 * 60 * 60 * 1000).toISOString()
      },
      {
        id: "mock_6",
        visitor_uuid: "vis_mock_uuid_106",
        created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Chimoio",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Manica",
        browser_name: "Chrome",
        browser_version: "125.0",
        os_name: "Android",
        device_model: "Huawei P30 Lite",
        screen_resolution: "360x780",
        language: "pt-MZ",
        session_duration: 85,
        visit_count: 1,
        page_visited: "/clinicas",
        ip_address: "102.220.12.3",
        last_active: new Date(Date.now() - 3.9 * 60 * 60 * 1000).toISOString()
      },
      {
        id: "mock_7",
        visitor_uuid: "vis_mock_uuid_107",
        created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Luanda",
        location_country: "Angola",
        location_country_code: "AO",
        location_region: "Luanda",
        browser_name: "Chrome Mobile",
        browser_version: "123.0",
        os_name: "Android",
        device_model: "Samsung Galaxy A54 5G",
        screen_resolution: "412x915",
        language: "pt-AO",
        session_duration: 15,
        visit_count: 2,
        page_visited: "/",
        ip_address: "197.94.200.12",
        last_active: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
      },
      {
        id: "mock_8",
        visitor_uuid: "vis_mock_uuid_108",
        created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        is_mobile: false,
        location_city: "Johannesburg",
        location_country: "África do Sul",
        location_country_code: "ZA",
        location_region: "Gauteng",
        browser_name: "Chrome",
        browser_version: "125.0",
        os_name: "Windows",
        device_model: "Dell XPS Laptop",
        screen_resolution: "1920x1200",
        language: "en-ZA",
        session_duration: 340,
        visit_count: 4,
        page_visited: "/transporte",
        ip_address: "196.23.4.156",
        last_active: new Date(Date.now() - 11.9 * 60 * 60 * 1000).toISOString()
      },
      {
        id: "mock_9",
        visitor_uuid: "vis_mock_uuid_109",
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        is_mobile: true,
        location_city: "Quelimane",
        location_country: "Moçambique",
        location_country_code: "MZ",
        location_region: "Zambézia",
        browser_name: "Opera Mini",
        browser_version: "78.0",
        os_name: "Android",
        device_model: "Tecno Spark 10 Pro",
        screen_resolution: "396x880",
        language: "pt-MZ",
        session_duration: 72,
        visit_count: 1,
        page_visited: "/",
        ip_address: "154.73.12.87",
        last_active: new Date(Date.now() - 23.9 * 60 * 60 * 1000).toISOString()
      },
      {
        id: "mock_10",
        visitor_uuid: "vis_mock_uuid_110",
        created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
        is_mobile: false,
        location_city: "Londres",
        location_country: "Reino Unido",
        location_country_code: "GB",
        location_region: "Greater London",
        browser_name: "Safari",
        browser_version: "17.0",
        os_name: "macOS",
        device_model: "Apple Mac (MacBook Pro)",
        screen_resolution: "1728x1117",
        language: "en-GB",
        session_duration: 110,
        visit_count: 6,
        page_visited: "/vagas",
        ip_address: "82.165.19.2",
        last_active: new Date(Date.now() - 35.9 * 60 * 60 * 1000).toISOString()
      }
    ];

    try {
      localStorage.setItem("zuca_local_visitors", JSON.stringify(mockVisitors));
      
      if (isSupabaseConfigured && supabase) {
        supabase.from("visitors").upsert(mockVisitors, { onConflict: 'visitor_uuid' }).then(({ error }) => {
          if (!error) {
            console.log("Mock unique data uploaded successfully to Supabase!");
            fetchVisitors();
          } else {
            console.warn("Could not upsert mock data into Supabase:", error);
            fetchVisitors();
          }
        });
      } else {
        fetchVisitors();
      }
    } catch (err) {
      console.warn("Failed to inject mock visitor records:", err);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  useEffect(() => {
    fetchVisitors();
  }, []);

  const totalLogsCount = visitors.length;
  const mobileCount = visitors.filter(v => v.is_mobile).length;
  const mobilePercentage = totalLogsCount > 0 ? Math.round((mobileCount / totalLogsCount) * 100) : 0;
  const averageDuration = totalLogsCount > 0 ? Math.round(visitors.reduce((acc, curr) => acc + (curr.session_duration || 0), 0) / totalLogsCount) : 0;

  // Total unique visits combined
  const totalVisitsCount = visitors.reduce((acc, curr) => acc + (curr.visit_count || 1), 0);

  // Find top location
  const locationCounts = {};
  visitors.forEach(v => {
    const loc = `${v.location_city || "Desconhecido"}, ${v.location_country_code || "MZ"}`;
    locationCounts[loc] = (locationCounts[loc] || 0) + 1;
  });
  let topLocation = "Maputo, MZ";
  let maxCount = 0;
  Object.entries(locationCounts).forEach(([loc, count]) => {
    if (count > maxCount) {
      maxCount = count;
      topLocation = loc;
    }
  });

  return (
    <div className="container mx-auto px-4 py-8 md:py-12 flex flex-col gap-8 min-h-[90vh] text-gray-200">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 border-b border-surface-light pb-6">
        <div className="flex flex-col gap-2">
          <Link href="/area-reservada" className="text-xs text-mint font-bold hover:underline flex items-center gap-1 uppercase tracking-wider">
            <ArrowLeft className="w-4 h-4" /> Voltar para Área Reservada
          </Link>
          <h1 className="text-3xl md:text-5xl font-black text-white tracking-tight flex items-center gap-3">
            Visitantes Únicos <span className="text-xs px-2.5 py-1 rounded-full border border-mint/30 bg-mint/10 text-mint font-bold animate-pulse">Monitor Ativo</span>
          </h1>
          <p className="text-gray-400 text-sm">
            Monitore o comportamento consolidado de cada visitante único do sistema Zuca.
          </p>
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={() => fetchVisitors(true)} 
            disabled={refetching}
            className="flex items-center gap-2 bg-surface hover:bg-surface-light border border-surface-light rounded-xl px-4 py-3 font-semibold text-sm transition-all"
          >
            <RefreshCw className={`w-4 h-4 text-mint ${refetching ? "animate-spin" : ""}`} /> Atualizar
          </button>
          
          <button 
            onClick={generateMockData}
            className="bg-mint text-charcoal hover:bg-white px-5 py-3 rounded-xl font-bold text-sm transition-all shadow-[0_0_15px_rgba(0,255,136,0.2)]"
          >
            Injetar 10 Visitantes Únicos
          </button>
        </div>
      </div>

      {/* Supabase Connection Status Card */}
      <div className={`p-6 rounded-2xl border flex flex-col md:flex-row items-start md:items-center justify-between gap-4 ${
        isSupabaseConfigured 
          ? "bg-mint/5 border-mint/20 text-mint" 
          : "bg-yellow-500/5 border-yellow-500/20 text-yellow-500"
      }`}>
        <div className="flex items-start gap-4">
          <div className={`p-3 rounded-xl shrink-0 mt-1 ${isSupabaseConfigured ? "bg-mint/10" : "bg-yellow-500/10"}`}>
            {isSupabaseConfigured ? (
              <ShieldCheck className="w-8 h-8 text-mint" />
            ) : (
              <AlertTriangle className="w-8 h-8 text-yellow-500" />
            )}
          </div>
          <div>
            <h3 className="text-lg font-bold text-white mb-1">
              Status do Supabase: {isSupabaseConfigured ? "Conectado por UUID Único" : "Simulado Localmente"}
            </h3>
            <p className="text-gray-400 text-sm max-w-2xl">
              {isSupabaseConfigured 
                ? `Ligação ativa com o projeto ${process.env.NEXT_PUBLIC_SUPABASE_URL}. Cada utilizador possui um identificador persistente e os seus acessos e tempo acumulados são atualizados na nuvem.`
                : "Os logs de visitantes estão atualmente a ser guardados apenas no armazenamento local do navegador (localStorage) para demonstração. Configure a conexão Supabase no seu ficheiro .env.local para ativação."
              }
            </p>
          </div>
        </div>
        <div className="text-xs font-semibold px-3.5 py-1.5 rounded-full border bg-charcoal">
          Modo Atual: <span className="uppercase text-white font-bold">{dataSource === "supabase" ? "Supabase Cloud" : "Local Simulado"}</span>
        </div>
      </div>

      {/* Metrics Summary Panels */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        
        {/* Metric 1: Total Unique Visitors */}
        <div className="bg-surface p-6 rounded-2xl border border-surface-light flex items-center justify-between">
          <div>
            <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Visitantes Únicos</span>
            <h4 className="text-3xl font-black text-white mt-1">{totalLogsCount}</h4>
          </div>
          <div className="p-3 bg-charcoal rounded-xl border border-surface-light">
            <Users className="w-6 h-6 text-mint" />
          </div>
        </div>

        {/* Metric 2: Total Visits (Visitas Acumuladas) */}
        <div className="bg-surface p-6 rounded-2xl border border-surface-light flex items-center justify-between">
          <div>
            <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Visitas Totais</span>
            <h4 className="text-3xl font-black text-white mt-1">{totalVisitsCount}</h4>
          </div>
          <div className="p-3 bg-charcoal rounded-xl border border-surface-light">
            <Eye className="w-6 h-6 text-mint" />
          </div>
        </div>

        {/* Metric 3: Avg Duration */}
        <div className="bg-surface p-6 rounded-2xl border border-surface-light flex items-center justify-between">
          <div>
            <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Tempo Acumulado Médio</span>
            <h4 className="text-3xl font-black text-white mt-1">{formatDuration(averageDuration)}</h4>
          </div>
          <div className="p-3 bg-charcoal rounded-xl border border-surface-light">
            <Clock className="w-6 h-6 text-mint" />
          </div>
        </div>

        {/* Metric 4: Top Location */}
        <div className="bg-surface p-6 rounded-2xl border border-surface-light flex items-center justify-between">
          <div>
            <span className="text-xs text-gray-400 font-bold uppercase tracking-wider">Local Principal</span>
            <h4 className="text-lg font-bold text-white mt-2 truncate max-w-[170px]">{topLocation}</h4>
          </div>
          <div className="p-3 bg-charcoal rounded-xl border border-surface-light">
            <MapPin className="w-6 h-6 text-mint" />
          </div>
        </div>

      </div>

      {/* Main Content Area: Table of Unique Visitors */}
      <div className="bg-surface rounded-2xl border border-surface-light overflow-hidden">
        <div className="p-6 border-b border-surface-light flex items-center justify-between">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <Compass className="w-5 h-5 text-mint" /> Relatório Consolidado de Visitantes Únicos
          </h2>
          <span className="text-xs text-gray-500 font-semibold">Atualização contínua por batimento de dados</span>
        </div>

        {isLoading ? (
          <div className="py-20 flex flex-col items-center justify-center gap-3">
            <RefreshCw className="w-8 h-8 text-mint animate-spin" />
            <span className="text-sm text-gray-400">A obter logs de visitantes únicos...</span>
          </div>
        ) : visitors.length === 0 ? (
          <div className="py-20 px-6 text-center max-w-md mx-auto flex flex-col items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-charcoal border border-surface-light flex items-center justify-center">
              <Users className="w-8 h-8 text-gray-600" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Nenhum visitante logado</h3>
              <p className="text-sm text-gray-400 mt-1">
                Ainda não foram registados acessos. Utilize o botão "Injetar 10 Visitantes Únicos" ou aceda a outras páginas no portal para iniciar o rastreio!
              </p>
            </div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-charcoal border-b border-surface-light text-xs text-gray-400 font-bold uppercase tracking-wider">
                  <th className="py-4 px-6">Localização & IP</th>
                  <th className="py-4 px-6">Dispositivo & Specs</th>
                  <th className="py-4 px-6">Navegador & OS</th>
                  <th className="py-4 px-6">Identificador UUID</th>
                  <th className="py-4 px-6">Visitas / Página</th>
                  <th className="py-4 px-6">Tempo Acumulado</th>
                  <th className="py-4 px-6 text-right">Última Atividade</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-light text-sm">
                {visitors.map((visitor) => (
                  <tr key={visitor.id} className="hover:bg-charcoal/40 transition-colors">
                    
                    {/* Geolocation Column */}
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-3">
                        <span className="text-2xl shrink-0" title={visitor.location_country}>
                          {getCountryFlag(visitor.location_country_code)}
                        </span>
                        <div className="flex flex-col">
                          <span className="font-bold text-white leading-tight">
                            {visitor.location_city || "Desconhecido"}
                          </span>
                          <span className="text-xs text-gray-400">
                            {visitor.location_country || "Moçambique"} • <span className="font-mono text-[10px] text-gray-500">{visitor.ip_address || "127.0.0.1"}</span>
                          </span>
                        </div>
                      </div>
                    </td>

                    {/* Device Specification Column */}
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-3">
                        {visitor.is_mobile ? (
                          <Smartphone className="w-5 h-5 text-mint shrink-0" />
                        ) : (
                          <Monitor className="w-5 h-5 text-gray-400 shrink-0" />
                        )}
                        <div className="flex flex-col">
                          <span className="font-semibold text-gray-200 flex items-center gap-1.5">
                            {visitor.device_model || "PC / Laptop"}
                          </span>
                          <span className="text-xs text-gray-500 flex items-center gap-1">
                            <Cpu className="w-3.5 h-3.5" /> Ecrã: {visitor.screen_resolution || "1920x1080"}
                          </span>
                        </div>
                      </div>
                    </td>

                    {/* Browser & OS Column */}
                    <td className="py-4 px-6">
                      <div className="flex flex-col">
                        <span className="font-semibold text-gray-200">
                          {visitor.browser_name} <span className="text-xs text-gray-500 font-mono">v{visitor.browser_version?.split('.')[0] || "X"}</span>
                        </span>
                        <span className="text-xs text-gray-400">
                          SO: {visitor.os_name || "Desconhecido"} • Idioma: {visitor.language || "pt"}
                        </span>
                      </div>
                    </td>

                    {/* Unique Identifier Column */}
                    <td className="py-4 px-6">
                      <span className="font-mono text-[11px] text-gray-400 bg-charcoal border border-surface-light px-2.5 py-1.5 rounded-lg block max-w-[120px] truncate" title={visitor.visitor_uuid}>
                        {visitor.visitor_uuid}
                      </span>
                    </td>

                    {/* Visits & Path Column */}
                    <td className="py-4 px-6">
                      <div className="flex flex-col gap-1">
                        <span className="text-xs text-gray-300 font-semibold">
                          Visitas: <strong className="text-mint">{visitor.visit_count || 1}</strong>
                        </span>
                        <span className="font-mono text-[10px] text-gray-500 truncate max-w-[110px]" title={visitor.page_visited}>
                          Rota: {visitor.page_visited || "/"}
                        </span>
                      </div>
                    </td>

                    {/* Accumulated Session Duration */}
                    <td className="py-4 px-6">
                      <div className="flex items-center gap-2">
                        {new Date() - new Date(visitor.last_active) < 25000 ? (
                          <span className="w-2.5 h-2.5 rounded-full bg-mint animate-ping shrink-0" title="Ativo Agora"></span>
                        ) : (
                          <span className="w-2.5 h-2.5 rounded-full bg-gray-600 shrink-0"></span>
                        )}
                        <span className="font-bold text-white font-mono">
                          {formatDuration(visitor.session_duration)}
                        </span>
                      </div>
                    </td>

                    {/* Last Active Timestamp */}
                    <td className="py-4 px-6 text-right text-gray-400 text-xs font-semibold">
                      {formatTimeAgo(visitor.last_active)}
                    </td>

                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* SQL Script guide */}
      <div className="bg-surface rounded-2xl border border-surface-light p-6 md:p-8 flex flex-col gap-6">
        <div className="flex flex-col gap-2">
          <h3 className="text-xl font-bold text-white flex items-center gap-2">
            <Terminal className="w-5 h-5 text-mint" /> Instalação da Tabela Única no Supabase
          </h3>
          <p className="text-sm text-gray-400">
            Esta versão utiliza a restrição <code className="text-mint font-mono">visitor_uuid UNIQUE</code> para lidar com upserts e evitar logs redundantes por utilizador.
          </p>
        </div>

        <div className="relative">
          <pre className="bg-charcoal p-5 rounded-xl border border-surface-light text-xs font-mono text-gray-300 overflow-x-auto max-h-[350px] leading-relaxed">
            {sqlSchema}
          </pre>
          
          <button
            onClick={copyToClipboard}
            className="absolute top-4 right-4 bg-surface hover:bg-surface-light border border-surface-light p-2.5 rounded-lg text-gray-300 hover:text-white transition-all"
            title="Copiar Script SQL"
          >
            {copied ? (
              <Check className="w-4 h-4 text-mint" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </button>
        </div>
      </div>

    </div>
  );
}
